---
title: "SDL MALL vs Paper"
author: "Adnan Mayof"
date: "2024-04-06"
output: html_document
---

 

```{r}
# Libraries
library(metafor)
library(meta)
library(clubSandwich)
library(effsize)
library(esc)

#install.packages("remotes")
#remotes::install_github("MathiasHarrer/dmetar")
library(dmetar)

```


```{r}
### MALL vs Paper-based learning
library(readxl)
OnlyPaperSelf <- read_excel("OnlyPaperSelf.xlsx")
View(OnlyPaperSelf)
attach(OnlyPaperSelf)


```



```{r}
#Defining variables
yiOnlyPaperSelf <- HedgesgOnlyPaperSelf
viOnlyPaperSelf <- VarianceOnlyPaperSelf
seiOnlyPaperSelf<- StandardErrorOnlyPaperSelf



```


```{r}
#resPaper <- rma.mv(yiOnlyPaperSelf,  viOnlyPaperSelf,data= OnlyPaperSelf)
#resPaper

resPaper <- rma.mv(yiOnlyPaperSelf,  viOnlyPaperSelf,  random = ~ 1 | StudyIdOnlyPaperSelf/AuthorOnlyPaperSelf,  data= OnlyPaperSelf)
resPaper

#The var.comp function in {dmetar} can be to calculate multilevel I2values.
resi2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2OnlyPaperSelf <- var.comp(resi2OnlyPaperSelf)
summary(i2OnlyPaperSelf)
##plot(i2OnlyPaperSelf)


```


```{r}
#Robust cluster variance estimation function clubSandwich::coef_test (variable, vcov = "CR2")
#The CR2 indicates that the standard errors will be corrected using Tipton and Pustejovsky's (2018)bias-reduced linearization estimator.
clubSandwich::coef_test(resPaper, vcov = "CR2") 
clubSandwich::conf_int(resPaper, vcov = "CR2")


```


```{r}
metafor::funnel(resPaper)
metafor::forest(resPaper)


```



```{r}
# fail-safe N computations
fsn(yiOnlyPaperSelf, viOnlyPaperSelf, seiOnlyPaperSelf, data=OnlyPaperSelf, type="Rosenthal")


```



```{r}
#Categorical and continuous Data
OnlyPaperSelf$`ApplicationTypeOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`ApplicationTypeOnlyPaperSelf`)
OnlyPaperSelf$`AssessmentTypeOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`AssessmentTypeOnlyPaperSelf`)
OnlyPaperSelf$`DeviceTypeOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`DeviceTypeOnlyPaperSelf`)
OnlyPaperSelf$`EducationalLevelOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`EducationalLevelOnlyPaperSelf`)
OnlyPaperSelf$`FeedbackOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`FeedbackOnlyPaperSelf`)
OnlyPaperSelf$`InterventionDurationOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`InterventionDurationOnlyPaperSelf`)
OnlyPaperSelf$`LanguageProficiencyOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`LanguageProficiencyOnlyPaperSelf`)
OnlyPaperSelf$`LearningContextOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`LearningContextOnlyPaperSelf`)
OnlyPaperSelf$`MotherTongueOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`MotherTongueOnlyPaperSelf`)
OnlyPaperSelf$`PublicationTypeOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`PublicationTypeOnlyPaperSelf`)
OnlyPaperSelf$`ResearchSettingsOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`ResearchSettingsOnlyPaperSelf`)
OnlyPaperSelf$`TargetLanguageOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`TargetLanguageOnlyPaperSelf`)
OnlyPaperSelf$`TargetLanguageSkillOnlyPaperSelf`<- as.factor(OnlyPaperSelf$`TargetLanguageSkillOnlyPaperSelf`)
str(OnlyPaperSelf)


```



```{r}
# Moderators

appOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ ApplicationTypeOnlyPaperSelf, method = "REML")
appOnlyPaperSelf
appi2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ ApplicationTypeOnlyPaperSelf, random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2appOnlyPaperSelf <- var.comp(appi2OnlyPaperSelf)
summary(i2appOnlyPaperSelf)
plot(i2appOnlyPaperSelf)


assessOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ AssessmentTypeOnlyPaperSelf)
assessOnlyPaperSelf
assessi2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ AssessmentTypeOnlyPaperSelf,random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2assessOnlyPaperSelf <- var.comp(assessi2OnlyPaperSelf)
summary(i2assessOnlyPaperSelf)
plot(i2assessOnlyPaperSelf)

deviceOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ DeviceTypeOnlyPaperSelf)
deviceOnlyPaperSelf
devi2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ DeviceTypeOnlyPaperSelf, random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2devOnlyPaperSelf <- var.comp(devi2OnlyPaperSelf)
summary(i2devOnlyPaperSelf)
plot(i2devOnlyPaperSelf)

edulevelOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ EducationalLevelOnlyPaperSelf)
edulevelOnlyPaperSelf
edui2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ EducationalLevelOnlyPaperSelf, random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2eduOnlyPaperSelf <- var.comp(edui2OnlyPaperSelf)
summary(i2eduOnlyPaperSelf)
plot(i2eduOnlyPaperSelf)

feedOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ FeedbackOnlyPaperSelf)
feedOnlyPaperSelf
feedi2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ FeedbackOnlyPaperSelf, random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2feedOnlyPaperSelf <- var.comp(feedi2OnlyPaperSelf)
summary(i2feedOnlyPaperSelf)
plot(i2feedOnlyPaperSelf)

interventionOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ InterventionDurationOnlyPaperSelf) 
interventionOnlyPaperSelf
interi2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ InterventionDurationOnlyPaperSelf, random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2interOnlyPaperSelf <- var.comp(interi2OnlyPaperSelf)
summary(i2interOnlyPaperSelf)
plot(i2interOnlyPaperSelf)

proficiencyOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ LanguageProficiencyOnlyPaperSelf)
proficiencyOnlyPaperSelf
proi2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ LanguageProficiencyOnlyPaperSelf, random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2proOnlyPaperSelf <- var.comp(proi2OnlyPaperSelf)
summary(i2proOnlyPaperSelf)
plot(i2proOnlyPaperSelf)

contextOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ LearningContextOnlyPaperSelf)
contextOnlyPaperSelf
coni2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ LearningContextOnlyPaperSelf,random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2conOnlyPaperSelf <- var.comp(coni2OnlyPaperSelf)
summary(i2conOnlyPaperSelf)
plot(i2conOnlyPaperSelf)

motherOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ MotherTongueOnlyPaperSelf)
motherOnlyPaperSelf
moi2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ MotherTongueOnlyPaperSelf, random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2moOnlyPaperSelf <- var.comp(moi2OnlyPaperSelf)
summary(i2moOnlyPaperSelf)
plot(i2moOnlyPaperSelf)

publicationOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ PublicationTypeOnlyPaperSelf)
publicationOnlyPaperSelf
pui2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ PublicationTypeOnlyPaperSelf, random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2puOnlyPaperSelf <- var.comp(pui2OnlyPaperSelf)
summary(i2puOnlyPaperSelf)
plot(i2puOnlyPaperSelf)

settingOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ ResearchSettingsOnlyPaperSelf)
settingOnlyPaperSelf
seti2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ ResearchSettingsOnlyPaperSelf, random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2setOnlyPaperSelf <- var.comp(seti2OnlyPaperSelf)
summary(i2setOnlyPaperSelf)
plot(i2setOnlyPaperSelf)

targetOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ TargetLanguageOnlyPaperSelf)
targetOnlyPaperSelf
tari2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ TargetLanguageOnlyPaperSelf, random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2tarOnlyPaperSelf <- var.comp(tari2OnlyPaperSelf)
summary(i2tarOnlyPaperSelf)
plot(i2tarOnlyPaperSelf)

skillOnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ TargetLanguageSkillOnlyPaperSelf)
skillOnlyPaperSelf
skilli2OnlyPaperSelf <- rma.mv(yiOnlyPaperSelf, viOnlyPaperSelf, mods = ~ TargetLanguageSkillOnlyPaperSelf, random = ~ 1 | AuthorOnlyPaperSelf/StudyIdOnlyPaperSelf,test = "t",data = OnlyPaperSelf, method = "REML")
i2skillOnlyPaperSelf <- var.comp(skilli2OnlyPaperSelf)
summary(i2skillOnlyPaperSelf)
plot(i2skillOnlyPaperSelf)




```


```{r}
# Regression

model1OnlyPaperSelf <- lm(yiOnlyPaperSelf ~ ApplicationTypeOnlyPaperSelf)
summary(model1OnlyPaperSelf)
clubSandwich::coef_test(model1OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model1OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

OnlyPaperSelf$ApplicationTypeOnlyPaperSelf <-relevel(OnlyPaperSelf$ApplicationTypeOnlyPaperSelf, ref = "SMS")
model1refPaper <- lm(yiOnlyPaperSelf ~ ApplicationTypeOnlyPaperSelf, data = OnlyPaperSelf)
summary(model1refPaper)
clubSandwich::coef_test(model1refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model1refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

model2OnlyPaperSelf <- lm(yiOnlyPaperSelf ~ AssessmentTypeOnlyPaperSelf)
summary(model2OnlyPaperSelf)
clubSandwich::coef_test(model2OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model2OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

OnlyPaperSelf$AssessmentTypeOnlyPaperSelf <-relevel(OnlyPaperSelf$AssessmentTypeOnlyPaperSelf, ref = "NR")
model2refPaper <- lm(yiOnlyPaperSelf ~ AssessmentTypeOnlyPaperSelf, data = OnlyPaperSelf)
summary(model2refPaper)
clubSandwich::coef_test(model2refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model2refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

model3OnlyPaperSelf <- lm(yiOnlyPaperSelf ~ DeviceTypeOnlyPaperSelf)
summary(model3OnlyPaperSelf)
clubSandwich::coef_test(model3OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model3OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

OnlyPaperSelf$DeviceTypeOnlyPaperSelf <-relevel(OnlyPaperSelf$DeviceTypeOnlyPaperSelf, ref = "Smartphone")
model13refPaper <- lm(yiOnlyPaperSelf ~ DeviceTypeOnlyPaperSelf, data = OnlyPaperSelf)
summary(model13refPaper)
clubSandwich::coef_test(model13refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model13refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

model4OnlyPaperSelf <- lm(yiOnlyPaperSelf ~ EducationalLevelOnlyPaperSelf)
summary(model4OnlyPaperSelf)
clubSandwich::coef_test(model4OnlyPaperSelf, vcov = "CR2", cluster = EducationalLevelOnlyPaperSelf)
clubSandwich::conf_int(model4OnlyPaperSelf, vcov = "CR2", cluster = EducationalLevelOnlyPaperSelf)

OnlyPaperSelf$EducationalLevelOnlyPaperSelf <-relevel(OnlyPaperSelf$EducationalLevelOnlyPaperSelf, ref = "Secondary")
model14refPaper <- lm(yiOnlyPaperSelf ~ EducationalLevelOnlyPaperSelf, data = OnlyPaperSelf)
summary(model14refPaper)
clubSandwich::coef_test(model14refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model14refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

model5OnlyPaperSelf <- lm(yiOnlyPaperSelf ~ FeedbackOnlyPaperSelf)
summary(model5OnlyPaperSelf)
clubSandwich::coef_test(model5OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model5OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

OnlyPaperSelf$FeedbackOnlyPaperSelf <-relevel(OnlyPaperSelf$FeedbackOnlyPaperSelf, ref = "Via Application")
model5refPaper <- lm(yiOnlyPaperSelf ~ FeedbackOnlyPaperSelf, data = OnlyPaperSelf)
summary(model5refPaper)
clubSandwich::coef_test(model5refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model5refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

model6OnlyPaperSelf <- lm(yiOnlyPaperSelf ~ InterventionDurationOnlyPaperSelf)
summary(model6OnlyPaperSelf)
clubSandwich::coef_test(model6OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model6OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

OnlyPaperSelf$InterventionDurationOnlyPaperSelf <-relevel(OnlyPaperSelf$InterventionDurationOnlyPaperSelf, ref = "Less than ten weeks")
model6refPaper <- lm(yiOnlyPaperSelf ~ InterventionDurationOnlyPaperSelf, data = OnlyPaperSelf)
summary(model6refPaper)
clubSandwich::coef_test(model6refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model6refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)


model7OnlyPaperSelf <- lm(yiOnlyPaperSelf ~ LanguageProficiencyOnlyPaperSelf)
summary(model7OnlyPaperSelf)
clubSandwich::coef_test(model7OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model7OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

OnlyPaperSelf$LanguageProficiencyOnlyPaperSelf <-relevel(OnlyPaperSelf$LanguageProficiencyOnlyPaperSelf, ref = "NR")
model7refPaper <- lm(yiOnlyPaperSelf ~ LanguageProficiencyOnlyPaperSelf, data = OnlyPaperSelf)
summary(model7refPaper)
clubSandwich::coef_test(model7refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model7refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

model8OnlyPaperSelf <- lm(yiOnlyPaperSelf ~ LearningContextOnlyPaperSelf)
summary(model8OnlyPaperSelf)
clubSandwich::coef_test(model8OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model8OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

OnlyPaperSelf$LearningContextOnlyPaperSelf <-relevel(OnlyPaperSelf$LearningContextOnlyPaperSelf, ref = "Mixed")
model8refPaper <- lm(yiOnlyPaperSelf ~ LearningContextOnlyPaperSelf, data = OnlyPaperSelf)
summary(model8refPaper)
clubSandwich::coef_test(model8refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model8refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

model9OnlyPaperSelf <- lm(yiOnlyPaperSelf ~ MotherTongueOnlyPaperSelf)
summary(model9OnlyPaperSelf)
clubSandwich::coef_test(model9OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model9OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

OnlyPaperSelf$MotherTongueOnlyPaperSelf <-relevel(OnlyPaperSelf$MotherTongueOnlyPaperSelf, ref = "Turkish")
model9refPaper <- lm(yiOnlyPaperSelf ~ MotherTongueOnlyPaperSelf, data = OnlyPaperSelf)
summary(model9refPaper)
clubSandwich::coef_test(model9refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model9refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

model10OnlyPaperSelf <- lm(yiOnlyPaperSelf ~ PublicationTypeOnlyPaperSelf)
summary(model10OnlyPaperSelf)
clubSandwich::coef_test(model10OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model10OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

OnlyPaperSelf$PublicationTypeOnlyPaperSelf <-relevel(OnlyPaperSelf$PublicationTypeOnlyPaperSelf, ref = "Dissertation")
model10refPaper <- lm(yiOnlyPaperSelf ~ PublicationTypeOnlyPaperSelf, data = OnlyPaperSelf)
summary(model10refPaper)
clubSandwich::coef_test(model10refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model10refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

model11OnlyPaperSelf <- lm(yiOnlyPaperSelf ~ ResearchSettingsOnlyPaperSelf)
summary(model11OnlyPaperSelf)
clubSandwich::coef_test(model11OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model11OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

OnlyPaperSelf$ResearchSettingsOnlyPaperSelf <-relevel(OnlyPaperSelf$ResearchSettingsOnlyPaperSelf, ref = "Second")
model11refPaper <- lm(yiOnlyPaperSelf ~ ResearchSettingsOnlyPaperSelf, data = OnlyPaperSelf)
summary(model11refPaper)
clubSandwich::coef_test(model11refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model11refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

model12OnlyPaperSelf <- lm(yiOnlyPaperSelf~ TargetLanguageOnlyPaperSelf)
summary(model12OnlyPaperSelf)
clubSandwich::coef_test(model12OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model12OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

OnlyPaperSelf$TargetLanguageOnlyPaperSelf <-relevel(OnlyPaperSelf$TargetLanguageOnlyPaperSelf, ref = "French")
model12refPaper <- lm(yiOnlyPaperSelf ~ TargetLanguageOnlyPaperSelf, data = OnlyPaperSelf)
summary(model12refPaper)
clubSandwich::coef_test(model12refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model12refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

model13OnlyPaperSelf <- lm(yiOnlyPaperSelf ~ TargetLanguageSkillOnlyPaperSelf)
summary(model13OnlyPaperSelf)
clubSandwich::coef_test(model13OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model13OnlyPaperSelf, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)

OnlyPaperSelf$TargetLanguageSkillOnlyPaperSelf <-relevel(OnlyPaperSelf$TargetLanguageSkillOnlyPaperSelf, ref = "Vocabulary")
model13refPaper <- lm(yiOnlyPaperSelf ~ TargetLanguageSkillOnlyPaperSelf, data = OnlyPaperSelf)
summary(model13refPaper)
clubSandwich::coef_test(model13refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)
clubSandwich::conf_int(model13refPaper, vcov = "CR2", cluster = OnlyPaperSelf$StudyIdOnlyPaperSelf)



```


```{r}
# Model 14
model14 <- lm(yiOnlyPaperSelf ~ DeviceTypeOnlyPaperSelf + TargetLanguageOnlyPaperSelf)
summary(model14)
# Adjusted R-squared: 0.2297 
# p-value: 0.03298

# Model 15
model15 <- lm(yiOnlyPaperSelf ~ DeviceTypeOnlyPaperSelf + InterventionDurationOnlyPaperSelf)
summary(model15)
# Adjusted R-squared: 0.2451 
# p-value: 0.04054

# Model 16
model16 <- lm(yiOnlyPaperSelf ~ DeviceTypeOnlyPaperSelf + ResearchSettingsOnlyPaperSelf)
summary(model16)
# Adjusted R-squared: 0.2297 
# p-value: 0.03298

# Model 17
model17 <- lm(yiOnlyPaperSelf ~ DeviceTypeOnlyPaperSelf + TargetLanguageOnlyPaperSelf)
summary(model17)
# Adjusted R-squared: 0.2297 
# p-value: 0.03298

# Model 18
model18 <- lm(yiOnlyPaperSelf ~ ApplicationTypeOnlyPaperSelf + AssessmentTypeOnlyPaperSelf + DeviceTypeOnlyPaperSelf + LanguageProficiencyOnlyPaperSelf + LearningContextOnlyPaperSelf + MotherTongueOnlyPaperSelf + PublicationTypeOnlyPaperSelf + ResearchSettingsOnlyPaperSelf + TargetLanguageOnlyPaperSelf + TargetLanguageSkillOnlyPaperSelf)
summary(model18)
# Insignificant

# Model 19
model19 <- lm(yiOnlyPaperSelf ~ ApplicationTypeOnlyPaperSelf + AssessmentTypeOnlyPaperSelf + DeviceTypeOnlyPaperSelf + LanguageProficiencyOnlyPaperSelf + LearningContextOnlyPaperSelf + MotherTongueOnlyPaperSelf + TargetLanguageOnlyPaperSelf + TargetLanguageSkillOnlyPaperSelf)
summary(model19)
# Adjusted R-squared: 0.9267 
# p-value: 0.0222

# Model 20
model20 <- lm(yiOnlyPaperSelf ~ ApplicationTypeOnlyPaperSelf + AssessmentTypeOnlyPaperSelf + DeviceTypeOnlyPaperSelf + LanguageProficiencyOnlyPaperSelf + MotherTongueOnlyPaperSelf + TargetLanguageOnlyPaperSelf + TargetLanguageSkillOnlyPaperSelf)
summary(model20)
# Without LearningContextOnlyPaperSelf 
# Adjusted R-squared: 0.8861 
# p-value: 0.01787

# Model 21
model21 <- lm(yiOnlyPaperSelf ~ ApplicationTypeOnlyPaperSelf + AssessmentTypeOnlyPaperSelf + DeviceTypeOnlyPaperSelf + LanguageProficiencyOnlyPaperSelf + MotherTongueOnlyPaperSelf + TargetLanguageSkillOnlyPaperSelf)
summary(model21)
# Without TargetLanguageOnlyPaperSelf
# Adjusted R-squared: 0.8861 
# p-value: 0.01787

# Model 22
model22 <- lm(yiOnlyPaperSelf ~ ApplicationTypeOnlyPaperSelf + AssessmentTypeOnlyPaperSelf + DeviceTypeOnlyPaperSelf + LanguageProficiencyOnlyPaperSelf + MotherTongueOnlyPaperSelf + TargetLanguageSkillOnlyPaperSelf)
summary(model22)
# Without TargetLanguageOnlyPaperSelf
# Adjusted R-squared: 0.8861 
# p-value: 0.01787

# Model 23
model23 <- lm(yiOnlyPaperSelf ~ ApplicationTypeOnlyPaperSelf + AssessmentTypeOnlyPaperSelf + DeviceTypeOnlyPaperSelf + LanguageProficiencyOnlyPaperSelf + LearningContextOnlyPaperSelf + MotherTongueOnlyPaperSelf + TargetLanguageOnlyPaperSelf)
summary(model23)
# Without TargetLanguageSkillOnlyPaperSelf
# Adjusted R-squared: 0.9293
# p-value: 0.00246

# Model 24
model24 <- lm(yiOnlyPaperSelf ~ ApplicationTypeOnlyPaperSelf + AssessmentTypeOnlyPaperSelf + DeviceTypeOnlyPaperSelf + LanguageProficiencyOnlyPaperSelf + LearningContextOnlyPaperSelf + MotherTongueOnlyPaperSelf)
summary(model24)
# Without TargetLanguageOnlyPaperSelf
# Adjusted R-squared: 0.9293
# p-value: 0.00246

# Model 25
model25 <- lm(yiOnlyPaperSelf ~ ApplicationTypeOnlyPaperSelf + AssessmentTypeOnlyPaperSelf + DeviceTypeOnlyPaperSelf + LanguageProficiencyOnlyPaperSelf + MotherTongueOnlyPaperSelf)
summary(model25)
# Without LearningContextOnlyPaperSelf
# Adjusted R-squared: 0.9018 
# p-value: 0.002152

# Model 26
model26 <- lm(yiOnlyPaperSelf ~ ApplicationTypeOnlyPaperSelf + AssessmentTypeOnlyPaperSelf + LanguageProficiencyOnlyPaperSelf + MotherTongueOnlyPaperSelf)
summary(model26)
# Without DeviceTypeOnlyPaperSelf
# Adjusted R-squared: 0.9018 
# p-value: 0.002152

# Model 27
model27 <- lm(yiOnlyPaperSelf ~ ApplicationTypeOnlyPaperSelf + LanguageProficiencyOnlyPaperSelf + MotherTongueOnlyPaperSelf)
summary(model27)
# Without DeviceTypeOnlyPaperSelf
# Adjusted R-squared: 0.7535  
# p-value: 0.01629



```
 