---
title: "SDL MALL Vs MALL"
author: "Adnan Mayof"
date: "2024-04-06"
output: html_document
---
 

```{r}
# Libraries
library(metafor)
library(meta)
#library(clubSandwich)
library(effsize)
library(esc)

#install.packages("remotes")
#remotes::install_github("MathiasHarrer/dmetar")
#library(dmetar)
 
 
```



```{r}
###  MALLL VS MMEF
library(readxl)
OnlyMALL <- read_excel("OnlyMALL.xlsx")
View(OnlyMALL)
attach(OnlyMALL)
 
```



```{r}
#Defining variables
yiOnlyMALL <- HedgesgOnlyMALL
viOnlyMALL <- VarianceOnlyMALL
seiOnlyMALL <- StandardErrorOnlyMALL
 
 
```



```{r}

# Attach OnlyMALL
attach(OnlyMALL)
 
 
```



```{r}
resMALL <- rma.mv(yiOnlyMALL, viOnlyMALL, random = ~ 1 | StudyIdOnlyMALL/AuthorOnlyMALL,data = OnlyMALL, method = "REML")
resMALL
 
 
```



```{r}
#The var.comp function in {dmetar} can be to calculate multilevel I2values.
#resi2MALL <- rma.mv(yiOnlyMALL, viOnlyMALL, random = ~ 1 | AuthorOnlyMALL/Samplesize,test = "t",data = OnlyMALL, method = "REML")
#i2MALL <- var.comp(resi2MALL)
#summary(i2MALL)
#plot(i2MALL)
 
 
```
 


```{r}
#Robust cluster variance estimation function #clubSandwich::coef_test (variable, vcov = "CR2")
#The CR2 indicates that the standard errors will be corrected using Tipton and Pustejovsky's (2018)bias-reduced linearization estimator.
#clubSandwich::coef_test(resMALL, vcov = "CR2") 
#clubSandwich::conf_int(resMALL, vcov = "CR2") 
 
 
```



```{r}
#metafor::funnel(resMALL)
#metafor::forest(resMALL)
 
 
```



```{r}
# fail-safe N computations
fsn(yiOnlyMALL, viOnlyMALL, seiOnlyMALL, data=OnlyMALL, type="Rosenthal")
 
 
```



```{r}
#Categorical and continuous Data
OnlyMALL$`ApplicationTypeOnlyMALL`<- as.factor(OnlyMALL$`ApplicationTypeOnlyMALL`)
OnlyMALL$`AssessmentTypeOnlyMALL`<- as.factor(OnlyMALL$`AssessmentTypeOnlyMALL`)
OnlyMALL$`DeviceTypeOnlyMALL`<- as.factor(OnlyMALL$`DeviceTypeOnlyMALL`)
OnlyMALL$`EducationalLevelOnlyMALL`<- as.factor(OnlyMALL$`EducationalLevelOnlyMALL`)
OnlyMALL$`FeedbackOnlyMALL`<- as.factor(OnlyMALL$`FeedbackOnlyMALL`)
OnlyMALL$`InterventionDurationOnlyMALL`<- as.factor(OnlyMALL$`InterventionDurationOnlyMALL`)
OnlyMALL$`LanguageProficiencyOnlyMALL`<- as.factor(OnlyMALL$`LanguageProficiencyOnlyMALL`)
OnlyMALL$`LearningContextOnlyMALL`<- as.factor(OnlyMALL$`LearningContextOnlyMALL`)
OnlyMALL$`MotherTongueOnlyMALL`<- as.factor(OnlyMALL$`MotherTongueOnlyMALL`)
OnlyMALL$`PublicationTypeOnlyMALL`<- as.factor(OnlyMALL$`PublicationTypeOnlyMALL`)
OnlyMALL$`ResearchSettingsOnlyMALL`<- as.factor(OnlyMALL$`ResearchSettingsOnlyMALL`)
OnlyMALL$`TargetLanguageOnlyMALL`<- as.factor(OnlyMALL$`TargetLanguageOnlyMALL`)
OnlyMALL$`TargetLanguageSkillOnlyMALL`<- as.factor(OnlyMALL$`TargetLanguageSkillOnlyMALL`)
str(OnlyMALL)


 
 
```



```{r}
# Moderators
appMALL <- rma.mv(yiOnlyMALL, viOnlyMALL, mods = ~ ApplicationTypeOnlyMALL, method = "REML")
appMALL

assessMALL <- rma.mv(yiOnlyMALL, viOnlyMALL, mods = ~ AssessmentTypeOnlyMALL)
assessMALL

deviceMALL <- rma.mv(yiOnlyMALL, viOnlyMALL, mods = ~ DeviceTypeOnlyMALL)
deviceMALL

feedMALL <- rma.mv(yiOnlyMALL, viOnlyMALL, mods = ~ FeedbackOnlyMALL)
feedMALL

interventionMALL <- rma.mv(yiOnlyMALL, viOnlyMALL, mods = ~ InterventionDurationOnlyMALL) 
interventionMALL

proficiencyMALL <- rma.mv(yiOnlyMALL, viOnlyMALL, mods = ~ LanguageProficiencyOnlyMALL)
proficiencyMALL

contextMALL <- rma.mv(yiOnlyMALL, viOnlyMALL, mods = ~ LearningContextOnlyMALL)
contextMALL

motherMALL <- rma.mv(yiOnlyMALL, viOnlyMALL, mods = ~ MotherTongueOnlyMALL)
motherMALL

publicationMALL <- rma.mv(yiOnlyMALL, viOnlyMALL, mods = ~ PublicationTypeOnlyMALL)
publicationMALL

targetMALL <- rma.mv(yiOnlyMALL, viOnlyMALL, mods = ~ TargetLanguageOnlyMALL)
targetMALL

skillMALL <- rma.mv(yiOnlyMALL, viOnlyMALL, mods = ~ TargetLanguageSkillOnlyMALL)
skillMALL
 
 
```



```{r}
# Regression
# Attach OnlyMALL
attach(OnlyMALL)

model1MALL <- lm(yiOnlyMALL ~ ApplicationTypeOnlyMALL)
summary(model1MALL)

model2MALL <- lm(yiOnlyMALL ~ AssessmentTypeOnlyMALL)
summary(model2MALL)

model3MALL <- lm(yiOnlyMALL ~ DeviceTypeOnlyMALL)
summary(model3MALL)

model5MALL <- lm(yiOnlyMALL ~ FeedbackOnlyMALL)
summary(model5MALL)

model6MALL <- lm(yiOnlyMALL ~ InterventionDurationOnlyMALL)
summary(model6MALL)

model7MALL <- lm(yiOnlyMALL ~ LanguageProficiencyOnlyMALL)
summary(model7MALL)

model8MALL <- lm(yiOnlyMALL ~ LearningContextOnlyMALL)
summary(model8MALL)

model9MALL <- lm(yiOnlyMALL ~ MotherTongueOnlyMALL)
summary(model9MALL)

model10MALL <- lm(yiOnlyMALL ~ PublicationTypeOnlyMALL)
summary(model10MALL)

model12MALL <- lm(yiOnlyMALL ~ TargetLanguageOnlyMALL)
summary(model12MALL)

model13MALL <- lm(yiOnlyMALL ~ TargetLanguageSkillOnlyMALL)
summary(model13MALL)

model14 <- lm(yiOnlyMALL ~ TargetLanguageSkillOnlyMALL)
summary(model14)

model15 <- lm(yiOnlyMALL ~ TargetLanguageSkillOnlyMALL + TargetLanguageOnlyMALL)
summary(model15)

model16 <- lm(yiOnlyMALL ~ ApplicationTypeOnlyMALL + AssessmentTypeOnlyMALL + LanguageProficiencyOnlyMALL + MotherTongueOnlyMALL)
summary(model16)

model17 <- lm(yiOnlyMALL ~ DeviceTypeOnlyMALL + FeedbackOnlyMALL +
                LearningContextOnlyMALL + PublicationTypeOnlyMALL + TargetLanguageOnlyMALL + TargetLanguageSkillOnlyMALL)
summary(model17)

model18 <- lm(yiOnlyMALL ~ ApplicationTypeOnlyMALL + AssessmentTypeOnlyMALL + DeviceTypeOnlyMALL + FeedbackOnlyMALL + LanguageProficiencyOnlyMALL +
                LearningContextOnlyMALL + MotherTongueOnlyMALL + PublicationTypeOnlyMALL + TargetLanguageOnlyMALL + TargetLanguageSkillOnlyMALL)
summary(model18)

model19 <- lm(yiOnlyMALL ~ ApplicationTypeOnlyMALL + AssessmentTypeOnlyMALL + DeviceTypeOnlyMALL + FeedbackOnlyMALL + LanguageProficiencyOnlyMALL +
                LearningContextOnlyMALL + MotherTongueOnlyMALL + PublicationTypeOnlyMALL + TargetLanguageOnlyMALL)
summary(model19)

model20 <- lm(yiOnlyMALL ~ AssessmentTypeOnlyMALL + TargetLanguageSkillOnlyMALL)
summary(model20)

model21 <- lm(yiOnlyMALL ~ DeviceTypeOnlyMALL + FeedbackOnlyMALL + ApplicationTypeOnlyMALL + TargetLanguageOnlyMALL + TargetLanguageOnlyMALL)
summary(model21)

model22 <- lm(yiOnlyMALL ~ TargetLanguageOnlyMALL + PublicationTypeOnlyMALL)
summary(model22)
 
```
 
 